### ISSUE TITLE
Publish the lib on npmjs ?

### ISSUE THREAD

**Issue by romainbessugesmeusy** [picturepan2/fileicon.css#4]
Hey there,
This lib looks rad ! I couldn't find it on npmjs and I believe you haven't published it yet. Is there something preventing you from doing so ?

**Comment by picturepan2** [comment]
Hi. Actually I plan to merge the fileicon.css into a new lightweight CSS framework [Project Spectre](https://github.com/picturepan2/spectre). There will be some refinements to the file icons as well. I will try to publish both of them once they are done. 

Thanks for watching.
- Yan Zhu

**Comment by picturepan2** [comment]
`npm install fileicon.css`
